// <auto-generated />
using System;
using CourceWork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourceWork.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourceWork.Models.CitizenAppeal", b =>
                {
                    b.Property<int>("AppealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appeal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Organization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("organization");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("show_id");

                    b.HasKey("AppealId")
                        .HasName("PK__CitizenA__DFAC766DB2A29641");

                    b.HasIndex("ShowId");

                    b.ToTable("CitizenAppeal", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__C52E0BA8625D2B30");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("GenreId")
                        .HasName("PK__Genre__18428D426CCEE2DA");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.HasKey("GuestId")
                        .HasName("PK__Guest__19778E352E3B73BE");

                    b.ToTable("Guest", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int")
                        .HasColumnName("month_number");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int")
                        .HasColumnName("week_number");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__C46A8A6FB9054CF4");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.ScheduleTvshow", b =>
                {
                    b.Property<int>("ScheduleTvshowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_tvshow_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleTvshowId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("show_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.HasKey("ScheduleTvshowId")
                        .HasName("PK__Schedule__B35EF5FE082385AC");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ShowId");

                    b.ToTable("Schedule_TVShow", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.Tvshow", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("show_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ShowId")
                        .HasName("PK__TVShow__2B97D71C540A5873");

                    b.HasIndex("GenreId");

                    b.ToTable("TVShow", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.TvshowEmployee", b =>
                {
                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("show_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("TvshowEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tvshow_employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TvshowEmployeeId"));

                    b.HasKey("ShowId", "EmployeeId")
                        .HasName("PK__TVShow_E__B7C537A655637BFA");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TVShow_Employee", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.TvshowGuest", b =>
                {
                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("show_id");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    b.Property<int>("TvshowGuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tvshow_guest_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TvshowGuestId"));

                    b.HasKey("ShowId", "GuestId")
                        .HasName("PK__TVShow_G__6A00AFFF1DFDF410");

                    b.HasIndex("GuestId");

                    b.ToTable("TVShow_Guest", (string)null);
                });

            modelBuilder.Entity("CourceWork.Models.CitizenAppeal", b =>
                {
                    b.HasOne("CourceWork.Models.Tvshow", "Show")
                        .WithMany("CitizenAppeals")
                        .HasForeignKey("ShowId")
                        .HasConstraintName("FK__CitizenAp__show___4AB81AF0");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("CourceWork.Models.ScheduleTvshow", b =>
                {
                    b.HasOne("CourceWork.Models.Schedule", "Schedule")
                        .WithMany("ScheduleTvshows")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedule___sched__4D94879B");

                    b.HasOne("CourceWork.Models.Tvshow", "Show")
                        .WithMany("ScheduleTvshows")
                        .HasForeignKey("ShowId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedule___show___4E88ABD4");

                    b.Navigation("Schedule");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("CourceWork.Models.Tvshow", b =>
                {
                    b.HasOne("CourceWork.Models.Genre", "Genre")
                        .WithMany("Tvshows")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK__TVShow__genre_id__3D5E1FD2");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CourceWork.Models.TvshowEmployee", b =>
                {
                    b.HasOne("CourceWork.Models.Employee", "Employee")
                        .WithMany("TvshowEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__TVShow_Em__emplo__412EB0B6");

                    b.HasOne("CourceWork.Models.Tvshow", "Show")
                        .WithMany("TvshowEmployees")
                        .HasForeignKey("ShowId")
                        .IsRequired()
                        .HasConstraintName("FK__TVShow_Em__show___403A8C7D");

                    b.Navigation("Employee");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("CourceWork.Models.TvshowGuest", b =>
                {
                    b.HasOne("CourceWork.Models.Guest", "Guest")
                        .WithMany("TvshowGuests")
                        .HasForeignKey("GuestId")
                        .IsRequired()
                        .HasConstraintName("FK__TVShow_Gu__guest__44FF419A");

                    b.HasOne("CourceWork.Models.Tvshow", "Show")
                        .WithMany("TvshowGuests")
                        .HasForeignKey("ShowId")
                        .IsRequired()
                        .HasConstraintName("FK__TVShow_Gu__show___440B1D61");

                    b.Navigation("Guest");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("CourceWork.Models.Employee", b =>
                {
                    b.Navigation("TvshowEmployees");
                });

            modelBuilder.Entity("CourceWork.Models.Genre", b =>
                {
                    b.Navigation("Tvshows");
                });

            modelBuilder.Entity("CourceWork.Models.Guest", b =>
                {
                    b.Navigation("TvshowGuests");
                });

            modelBuilder.Entity("CourceWork.Models.Schedule", b =>
                {
                    b.Navigation("ScheduleTvshows");
                });

            modelBuilder.Entity("CourceWork.Models.Tvshow", b =>
                {
                    b.Navigation("CitizenAppeals");

                    b.Navigation("ScheduleTvshows");

                    b.Navigation("TvshowEmployees");

                    b.Navigation("TvshowGuests");
                });
#pragma warning restore 612, 618
        }
    }
}
